neo4j:
  uri: bolt://localhost:25123
  user: neo4j
  database: neo4j
dataset_version: v3
results_tag: v3_qgprops
models_registry: config/models.yaml
active_model: mistral7b
ad: null
dis: null
benchmark: data/benchmark-v3.json
schema_linker_inference: config/schema_linker_inference.yaml
use_embedding_model: true
qg_include_properties: true
results_dir: results/
